### ISSUE TITLE
这个不会自动答题吧？

### ISSUE THREAD

**Issue by W285887933** [smileboywtu/MillionHeroAssistant#1]
每次运行了python3 main.py都需要手动提交

**Comment by smileboywtu** [comment]
对的 目前暂时是 帮你在网上找到合适的答案，不能自动提交，辅助你答题

**Comment by Sbwillbealier** [comment]
Traceback (most recent call last):
  File "main.py", line 78, in <module>
    main()
  File "main.py", line 69, in main
    print("\n".join(sentences))
TypeError: sequence item 0: expected str instance, Sentence found
报这个错误？

**Comment by smileboywtu** [comment]
已经修复

**Comment by smileboywtu** [comment]
@Sbwillbealier

**Comment by smileboywtu** [comment]
请使用分支 目前可以得知选项，自动选择待有人提交
