### ISSUE TITLE
学习了

### ISSUE THREAD

**Issue by HELLKING66666** [smileboywtu/MillionHeroAssistant#10]
\u63a5\u53e3\u914d\u7f6e\u4e4b\u7c7b\u7684\u4e1c\u897f\u6253\u7801\u54e6

**Comment by smileboywtu** [comment]
这是啥

**Comment by smileboywtu** [comment]
如果还有新的问题请重开issue 这个我先关了  欢迎骚扰

**Comment by HELLKING66666** [comment]
没事哇，只是觉得APIKEY不该丢出来~

2018-01-11 19:07 GMT+08:00 Bob <notifications@github.com>:
