### ISSUE TITLE
提出两个改进方向

### ISSUE THREAD

**Issue by kakalote2008** [smileboywtu/MillionHeroAssistant#11]
首先是免费OCR引擎，百度的免费额度只有每天500次，无法多人同时使用，汉王的则需要收费。推荐ocr.space，每个key每月有25000次调用，多用几个邮箱可以申请到多个key轮流使用。识别精准度我个人测试是没问题的，比google的tesseract强太多，tesseract的中文真的太烂了。
第二个就是ios的wda了，这个我看已经在roadmap里了貌似。
如果方向认同，我可以参与开发，谢谢。

**Comment by smileboywtu** [comment]
欢迎 加入 可以加我微信讨论

**Comment by kakalote2008** [comment]
嗯，那我先帮忙接入ocr.space吧

**Comment by smileboywtu** [comment]
好的 thanks

**Comment by smileboywtu** [comment]
这个先关了啊 有问题欢迎在开iussu骚扰
