### ISSUE TITLE
 Max retries exceeded with url

### ISSUE THREAD

**Issue by Matcha00** [smileboywtu/MillionHeroAssistant#15]
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8100): Max retries exceeded with url: /screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10b4954e0>: Failed to establish a new connection: [Errno 61] Connection refused',))

Process finished with exit code 1

**Comment by smileboywtu** [comment]
我看你这个使用了代理，另外你怎么访问的url也很奇怪哦，你先关掉你的代理 再试一试

**Comment by smileboywtu** [comment]
这个还有问题吗，没有问题我管了哦， 如果有新的问题欢迎骚扰
