### ISSUE TITLE
knearby分支识别成功无法搜索

### ISSUE THREAD

**Issue by Hyper-Devil** [smileboywtu/MillionHeroAssistant#20]
![tim 20180112120714](https://user-images.githubusercontent.com/35343157/34859704-ed01096c-f792-11e7-8cf6-866bef0b6ba0.png)

**Comment by smileboywtu** [comment]
谢谢 我测试一下 你可以提供下你的那个 screenshots里面的 qa.txt文件吗

**Comment by smileboywtu** [comment]
更新代码
