### ISSUE TITLE
你好，运行出现这个，请问是什么原因

### ISSUE THREAD

**Issue by liulance** [smileboywtu/MillionHeroAssistant#21]
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    from terminaltables import AsciiTable
ModuleNotFoundError: No module named 'terminaltables'

麻烦看看，谢谢，mac本，系统10.13

**Comment by smileboywtu** [comment]
pip install terminaltable 
推荐使用 最新代码 准确率更高

**Comment by liulance** [comment]
现在可以了，我运行项目的时候，为什么都是同一个题目？谢谢

**Comment by smileboywtu** [comment]
adb 看看是不是连接了 使用了手机的截图的

**Comment by liulance** [comment]
对啊，我用的手机截图测试的，这个不能用截图么？必须得运行答题的app嘛？

**Comment by smileboywtu** [comment]
可以用截图，麻烦粘贴下输出

**Comment by lllmmmfff** [comment]
我也报错
Traceback (most recent call last):
File "main.py", line 14, in 
from terminaltables import AsciiTable
ModuleNotFoundError: No module named 'terminaltables'

但是问题是，我已经安装了requirements了

**Comment by smileboywtu** [comment]
这个我最近发现了是windows上看32和64位的问题，明天微信或者qq联系我
