### ISSUE TITLE
缺少keyboard模块

### ISSUE THREAD

**Issue by jiashie** [smileboywtu/MillionHeroAssistant#22]
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    import keyboard
ModuleNotFoundError: No module named 'keyboard'

**Comment by ttentau** [comment]
我也是这个问题

**Comment by smileboywtu** [comment]
pip install -r

**Comment by smileboywtu** [comment]
pip install keyboard

**Comment by jiashie** [comment]
发现缺少的module不是一个两个啊，pip install -r requirements.txt后仍然一运行要根据提示逐步补全

**Comment by ttentau** [comment]
pip install keyboard 就好了 -- ！

**Comment by smileboywtu** [comment]
这个正在修复中

**Comment by smileboywtu** [comment]
已经修复 麻烦使用最新的代码 主干代码 谢谢支持
