### ISSUE TITLE
baidu api error:  No permission to access data

### ISSUE THREAD

**Issue by mobbjelly** [smileboywtu/MillionHeroAssistant#23]
这个是什么错？我申请了新的百度 appId 报的
![image](https://user-images.githubusercontent.com/8497784/34880538-ba65b3e6-f7eb-11e7-8b0e-4b1a9b9d2243.png)

**Comment by smileboywtu** [comment]
麻烦提供详细的报错信息 最好能加群 后截图

**Comment by smileboywtu** [comment]
可以加我微信 现在有详细的文档了
