### ISSUE TITLE
为什么百度ocr api配置改成自己的却还提示公共api已达使用上限？

### ISSUE THREAD

**Issue by lweo** [smileboywtu/MillionHeroAssistant#24]
特意上了自己的百度账号看了，今天才使用了80次。。

> 按Enter键开始，按ESC键退出...
capture time:  22:16:12
6112 KB/s (103321 bytes in 0.016s)
screen width: 1080, screen height: 1920
baidu api error:  Open api daily request limit reached
text not recognize

**Comment by lweo** [comment]
@smileboywtu 那怎么改成普通识别？

**Comment by lweo** [comment]
@smileboywtu config里的设置是普通识别

**Comment by smileboywtu** [comment]
api_version是0 是吗？ 如果是的话 可以上百度云看一看咋回事

**Comment by smileboywtu** [comment]
还有问题吗，如果还有的话欢迎再次骚扰
