### ISSUE TITLE
代码手误

### ISSUE THREAD

**Issue by 279632990** [smileboywtu/MillionHeroAssistant#25]
main.py里面46行 get_text_from_image写成了get_test_from_image，手误了吧

**Comment by smileboywtu** [comment]
谢谢我看看

**Comment by 279632990** [comment]
main.py第120行 question_obj.value = question 这里linux系统报错bytes or integer address expected instead of str instance，
改成question_obj.value = bytes(question,encoding='utf-8')好些吧？
另外下一行keyboard.press("space") 我实在不知道为何没有起到回调作用，浏览器不搜答案，
太晚了 睡了睡了

**Comment by smileboywtu** [comment]
这个我看了 已经改到最新的代码中了 你可以checkout最新的代码
