### ISSUE TITLE
出现substring not found

### ISSUE THREAD

**Issue by azazel777** [smileboywtu/MillionHeroAssistant#28]
有时候, 我看题目和选项都识别正常, 但是没有分析结果,提示substring not found. 这个问题主要是因为什么, 由于没有录屏,所以无法重现,抱歉.

**Comment by lweo** [comment]
同楼上

**Comment by Jortana** [comment]
同楼上

**Comment by SumDev** [comment]
看了下代码，貌似是因为搜索的结果没有和给出选项相匹配的关键字，抛出了这样的错误。希望作者优化一下。

**Comment by smileboywtu** [comment]
正在火速优化中

**Comment by azazel777** [comment]
多谢， 我刚才又出现了这个问题，并进行了截图，推测是答案文本中出现了特殊字符，希望能够提交搜索前进行过滤。不过我是win10英文版环境，可能是我系统语言的问题。
![wechat image_20180113152402](https://user-images.githubusercontent.com/27997666/34903897-d2aa2024-f875-11e7-9e43-52556f5e11f9.png)

**Comment by CharmingCheung** [comment]
![wechatimg66](https://user-images.githubusercontent.com/16662340/34903922-7169fda6-f876-11e7-93c2-e7e3cc674cf8.jpeg)
同出现此问题

**Comment by xilovesyu** [comment]
同出现上述问题

**Comment by luyiming** [comment]
bug 已修复，等待 merge
