### ISSUE TITLE
相似度猜测准确率太低

### ISSUE THREAD

**Issue by W-Jie** [smileboywtu/MillionHeroAssistant#3]
![default](https://user-images.githubusercontent.com/9733682/34754216-5c292376-f5f7-11e7-9a78-87a4cd224943.png)
![default](https://user-images.githubusercontent.com/9733682/34754223-612ef1fc-f5f7-11e7-99ee-cf957380febc.png)
![default](https://user-images.githubusercontent.com/9733682/34754228-6a24bcc4-f5f7-11e7-9e8c-9d50f6c4767b.png)

**Comment by smileboywtu** [comment]
谢谢 提交， 这个正在改进中，有想法可以加微信交流

**Comment by woshienn** [comment]
建议：如果出现要求 选择“。。。不是。。”，则关联率最低的为正确项，另外题目出现双行无法识别全。

**Comment by lihuangshuaige** [comment]
同感  准确率不是很高

**Comment by smileboywtu** [comment]
哈哈 可以试一下 新分支 不一样的惊喜
