### ISSUE TITLE
调用浏览器出错

### ISSUE THREAD

**Issue by lweo** [smileboywtu/MillionHeroAssistant#30]
必须要满足指定版本的浏览器才能调用？

`D:\搜狗高速下载\MillionHeroAssistant-master0113\MillionHeroAssistant-master>python main.py

    请在答题开始前就运行程序，
    答题开始的时候按Enter预测答案

按Enter键开始，按ESC键退出...
capture time:  14:25:12
6308 KB/s (586698 bytes in 0.090s)
screen width: 1080, screen height: 1920

浏览器加载失败
Message: session not created exception: Chrome version must be >= 62.0.3202.0
  (Driver info: chromedriver=2.35.528161 (5b82f2d2aae0ca24b877009200ced9065a772e73),platform=Windows NT 10.0.10586 x86_64)

Process Process-1:
Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "D:\Program Files\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "D:\搜狗高速下载\MillionHeroAssistant-master0113\MillionHeroAssistant-master\core\chrome_search.py", line 61, in run_browser
    browser.quit()
UnboundLocalError: local variable 'browser' referenced before assignment
------------------------------------------------------------------------
5动漫形象“史努比”出自于漫画?
------------------------------------------------------------------------
《花生漫画》
《狗狗漫画》
《史努比》
微信用户58656213697750复活码3697750复活码
3697750复活码3697750复码3697750复活码
substring not found
欢迎下次使用

    请在答题开始前就运行程序，
    答题开始的时候按Enter预测答案

按Enter键开始，按ESC键退出...`

**Comment by smileboywtu** [comment]
你好请下载最新的chrome浏览器

**Comment by smileboywtu** [comment]
另外需要更新代码了

**Comment by lweo** [comment]
@smileboywtu 不能调用IE吗？更新chrome我怕把我原来的数据弄没

还有代码不能识别《》，问题有书名号就会substring not found

**Comment by smileboywtu** [comment]
书名问题我晚上看下 
ie 由于兼容性不行 不推荐

**Comment by smileboywtu** [comment]
书名问题已经修复了 @lweo 
请使用最新版本

**Comment by lweo** [comment]
@smileboywtu   谢谢！希望作者继续优化，做得更加智能 ：）
