### ISSUE TITLE
有时候没有截上屏会报错

### ISSUE THREAD

**Issue by xilovesyu** [smileboywtu/MillionHeroAssistant#35]
capture time:  16:23:19
adb: error: remote object '/storage/emulated/0/screenshot.png' does not exist
screen width: 1080, screen height: 1920

**Comment by smileboywtu** [comment]
这个路径我看是错的，用的是模拟器吗

**Comment by xilovesyu** [comment]
路径是对的用的小米手机，只是偶尔出错。换成其他手机就没有出错。难道是手机的锅

**Comment by smileboywtu** [comment]
小米手机的截图会自动增加后缀 找不到文件 所以尽量不要用小米
