### ISSUE TITLE
关于orc.space api key

### ISSUE THREAD

**Issue by PiscesCNYu** [smileboywtu/MillionHeroAssistant#38]
今天试了下，晚上一直回车，就是没有去识别，截取正确的。可能是使用次数过多
然后用自己的百度接口
ORC的知道 
有个orc.space
api key =“”” 这里是哪个，百度云没有找到这个相关的Key。这是什么

**Comment by sjm1992st** [comment]
https://cloud.baidu.com/
点文字识别 登录控制台 创建应用

**Comment by PiscesCNYu** [comment]
@sjm1992st 这个ocr.space api key 就是创建应用的app_Key吗
### baidu orc
app_id = ""
app_key = ""
app_secret = ""	

### ocr.space
api_key = "6c851da45688957"

**Comment by crimsonskyrem** [comment]
我也没找到
顺带，我用的自己的API还是会卡顿
因为免费服务里有一项QPS限制，不保证并发

**Comment by sjm1992st** [comment]
@PiscesCNYu 对 我用的百度的

**Comment by PiscesCNYu** [comment]
@sjm1992st 感谢，我试试

**Comment by smileboywtu** [comment]
非常感谢回答，如果还是有问题欢迎骚扰
