### ISSUE TITLE
获取出来的问题是乱码

### ISSUE THREAD

**Issue by renbinming** [smileboywtu/MillionHeroAssistant#39]
win7，cmd 和 powershell 用过了，交互式正常，但是获取图片的问题和答案是乱码。请问怎么解决。

**Comment by smileboywtu** [comment]
cmd powershell 的终端要设置下编码

**Comment by smileboywtu** [comment]
http://blog.csdn.net/zhang_snow/article/details/62088725

**Comment by smileboywtu** [comment]
如果还是有问题请提交新的issue
