### ISSUE TITLE
感谢您的开源 完美运行 请问能不能适配芝士超人的答题界面？

### ISSUE THREAD

**Issue by NSDie** [smileboywtu/MillionHeroAssistant#40]

**Comment by smileboywtu** [comment]
又这个计划

**Comment by NSDie** [comment]
嗯 先期待一下。

**Comment by luyiming** [comment]
@NSDie 可以发一张芝士超人答题界面时的截屏吗？全屏的。如果有的话很快就能做适配了。

**Comment by NSDie** [comment]
忘了截 ，明天给你！

**Comment by NSDie** [comment]
![screenshot_20180114-123357](https://user-images.githubusercontent.com/24970218/34912960-1a6adb24-f92a-11e7-87e7-7bc026f1f6b6.png)
![Uploading Screenshot_20180114-123619.png…]()

**Comment by NSDie** [comment]
@luyiming  可以吗

**Comment by smileboywtu** [comment]
正在尝试适配中 敬请期待

**Comment by NSDie** [comment]
我自己修改了一下config中的参数 改完了。。

**Comment by NSDie** [comment]
可以关了  你需要参数吗

**Comment by smileboywtu** [comment]
需要谢谢提供

**Comment by takokay** [comment]
请问下这几个参数都是怎么确定的？

**Comment by NSDie** [comment]
'芝士超人': (55/1080, 300/1920, 1025/1080, 1200/1920)

**Comment by smileboywtu** [comment]
已经测试并提交
