### ISSUE TITLE
请问夜神模拟器怎么不能自动截图呢

### ISSUE THREAD

**Issue by inverter18** [smileboywtu/MillionHeroAssistant#41]

**Comment by inverter18** [comment]
按Enter键开始，按ESC键退出...
capture time:  13:28:27
[Errno 2] No such file or directory: 'screenshots\\screenshot.png'

**Comment by smileboywtu** [comment]
如果是小米手机 请微信联系我，目前兼容了跳一跳的方案，但是可能需要手动改下代码
