### ISSUE TITLE
对于冲顶的适配还是有点问题啊，提几个建议~

### ISSUE THREAD

**Issue by lweo** [smileboywtu/MillionHeroAssistant#42]
1.有时会把评论第一行也识别到选项里了，冲顶所有题都是3个选项，可以按识别选项数目判断，达到3个就过滤其他的识别内容；
![screenshot0114_131033](https://user-images.githubusercontent.com/2786659/34913160-6f068718-f930-11e7-83d8-28926865bcc8.png)
这个识别出来是：

`------------------------------------------------------------------------
SWOT分析法中,"S"是什么意优势劣势机会阿拉玉→19680363
------------------------------------------------------------------------
7.SWOT分析法中,"S"是什么意
优势
劣势
机会
阿拉玉→19680363
+----------------------------+------+
| 选项                       | 同比 |
+----------------------------+------+
| 机会                       | 16   |
| 优势                       | 12   |
| 劣势                       | 11   |
| 阿拉玉→19680363            | 6    |
| 7.SWOT分析法中,"S"是什么意 | 0    |
+----------------------------+------+
************************************************************************
肯定回答(**)：  机会
否定回答(  )：  7.SWOT分析法中,"S"是什么意
************************************************************************
use 3.4445133209228516 秒
欢迎下次使用`

2.搜索能不能去掉题号？题号的数字对搜索结果还是有影响的…

3.为什么我在chrome_search文件里的browser.get("http://www.baidu.com") 改为google，能打开google，但一识别问题chrome就退出了？如果我想默认调用google搜索，我该怎么设置？分词搜索推荐答案是用的百度知道吧，我想结合百度和google的结果综合判断。。

**Comment by jozhn** [comment]
2.去掉题号用最蠢的方法每次遇到数字和.的组合就去掉，自己写代码改改也行。
3.注意谷歌后面的参数是'search?q='加上文本，百度的是's?wd='。

**Comment by lweo** [comment]
@jozhn 你是说的这个项目吗？
作者的代码并没有采用wd=参数这种形式进行搜索啊（他的整个代码库里都没搜到s?wd=），它好像的调用chromedriver，不懂原理

去掉题号怎么改？不懂其代码逻辑。。

**Comment by jozhn** [comment]
@lweo 代码在baiduzhidao.py里：
```
    headers = {
        # "Cache-Control": "no-cache",
        "Host": "www.baidu.com",
        "User-Agent": random.choice(Agents)
    }
    params = {
        "wd": keyword.encode("gbk")
    }
    resp = requests.get("http://www.baidu.com/s", params=params, headers=headers, timeout=timeout)
```
改成
```
    headers = {
        # "Cache-Control": "no-cache",
        "Host": "www.google.com",
        "User-Agent": random.choice(Agents)
    }
    params = {
        "q": keyword.encode("gbk")
    }
    resp = requests.get("http://www.google.com/search", params=params, headers=headers, timeout=timeout)
```
应该就行了

**Comment by lweo** [comment]
@jozhn 

还是不能搜索，浏览器闪退

> Process Process-1:
Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "D:\Program Files\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "D:\搜狗高速下载\MillionHeroAssistant-d0901cf4bd08c0ba866f36b4986cb3ae668a0025\core\chrome_search.py", line 59, in run_browser
    browser_search(browser, question)
  File "D:\搜狗高速下载\MillionHeroAssistant-d0901cf4bd08c0ba866f36b4986cb3ae668a0025\core\chrome_search.py", line 72, in browser_search
    elem = browser.find_element_by_id("kw")
  File "D:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 351, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "D:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 955, in find_element
    'value': value})['value']
  File "D:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "D:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"kw"}
  (Session info: chrome=63.0.3239.132)
  (Driver info: chromedriver=2.35.528161 (5b82f2d2aae0ca24b877009200ced9065a772e73),platform=Windows NT 10.0.10586 x86_64)

**Comment by jozhn** [comment]
更新chrome到最新版

**Comment by jozhn** [comment]
还有问题是搜索会带个.这个没影响其实。。你也可以改代码完美一点，不会就算了。

**Comment by lweo** [comment]
@jozhn 谢了！baiduzhidao.py里host和搜索是不是不用改，那个是匹配相似度做推荐答案用的吧？

**Comment by lweo** [comment]
@jozhn  发现了改了chrome search，浏览器是可以打开google进行搜索了，但推荐答案对于任何问题都是0，
请教下怎么改推荐答案用百度知道的结果，同时打开浏览器搜索用google的？

**Comment by jozhn** [comment]
baiduzhidao.py恢复原样就行了

**Comment by lweo** [comment]
@jozhn 改了chrome search，代码推荐的答案对于任何问题都是0，

**Comment by smileboywtu** [comment]
冲顶的这个适配目前已经全部结束，另外关于任何问题都是0的情况目前已经找到修复办法，预计最近会给出，如果有新的问题 请再开issue
