### ISSUE TITLE
怎么禁止模拟器连接adb？

### ISSUE THREAD

**Issue by lweo** [smileboywtu/MillionHeroAssistant#43]
每次一开模拟器，手机adb就掉了，要重复连，我只想用模拟器答题，而手机连接电脑运行答题程序

**Comment by smileboywtu** [comment]
那就不要开启开发者模式吧 
默认不会链接adb的

**Comment by lweo** [comment]
@smileboywtu 模拟器怎么禁止开发者模式？我关闭了模拟器root，还是默认连接adb。。。

**Comment by smileboywtu** [comment]
什么模拟器哦

**Comment by lweo** [comment]
@smileboywtu 比如夜神

**Comment by smileboywtu** [comment]
夜神的话  需要`adb connect `默认是不执行的 如果你需要关闭自动链接 建议将 use monitor 改成false
