### ISSUE TITLE
图片匹配好像有问题

### ISSUE THREAD

**Issue by archer4117** [smileboywtu/MillionHeroAssistant#44]
crop_area = crop_areas[game_type] 这行代码算出来的一直都是（0，0，0，0）。需要调整什么配置吗

**Comment by smileboywtu** [comment]
你方便加我个微信我来看看 正常情况下不会有这个问题的

**Comment by archer4117** [comment]
crop_areas 里面的分数因为分子比分母小 所以除出来全是0 。是py2 和py3的区别导致的吗。按照道理来说应该是个比例系数。我改成固定的了。

**Comment by smileboywtu** [comment]
是的 目前已经修复了 自动适配不需要调整了 欢迎再次骚扰
