### ISSUE TITLE
能不能在终端窗口输出搜索结果的前10项内容？

### ISSUE THREAD

**Issue by lweo** [smileboywtu/MillionHeroAssistant#47]
去掉搜索结果的标题项，只留预览内容，最好是突出显示问题的关键词，更方便找答案，（当然推荐答案还是放到最后面，第一眼就能看到）这样比看2个窗口的结果要省些时间。。

**Comment by smileboywtu** [comment]
wonderful idea 谢谢 十分赞成这个想法

**Comment by smileboywtu** [comment]
新增知识库，该想法将会在知识库上面，另外高亮关键字

**Comment by smileboywtu** [comment]
这个建议暂时不予采纳了，显示多了你也看不过的 就10秒
