### ISSUE TITLE
不同运行方法出现了不同的问题，求教。

### ISSUE THREAD

**Issue by Deancup** [smileboywtu/MillionHeroAssistant#48]
使用cmd命令行运行时
报错如下，
![image](https://user-images.githubusercontent.com/25227084/34949333-bfada2d0-fa4a-11e7-8a8b-bda13678d0e1.png)
使用git bash或者pycharm不报错，但是程序未执行便显示
![image](https://user-images.githubusercontent.com/25227084/34949391-f2f30db0-fa4a-11e7-95e6-510bb31c6828.png)

浏览器可打开，但是无内容，程序不报错。不返回结果。

**Comment by smileboywtu** [comment]
注意由于使用的是相对目录，python的话需要设置pythonpath，如果在main.py文件夹中的话，那么就不需要设置pythonpath了

**Comment by Deancup** [comment]
![image](https://user-images.githubusercontent.com/25227084/34967680-829bab9e-fa9f-11e7-9b54-86e2fed2c3e6.png)
程序并无报错，只是没有结果，未显示任何内容，浏览器可自动打开，但是无检索

**Comment by smileboywtu** [comment]
请使用最新版，如果有类似问题 再开一个issue吧 @Deancup
