### ISSUE TITLE
改模拟器的配置文件的在哪里啊

### ISSUE THREAD

**Issue by XueHuagao** [smileboywtu/MillionHeroAssistant#50]
不想用夜神 用的bluestacks，找不到配置文件

**Comment by smileboywtu** [comment]
这个可以随意改，没的啥配置 就是注意下 Android.py文件中的adb init 默认连的是夜神的62001你看看是否需要修改

**Comment by smileboywtu** [comment]
这个还有问题吗，如果没有什么问题，我准备关了，另外有新的问题欢迎再次骚扰

**Comment by lweo** [comment]
@smileboywtu   Android.py文件里没搜到init  和62001…
