### ISSUE TITLE
编码报错！

### ISSUE THREAD

**Issue by NSDie** [smileboywtu/MillionHeroAssistant#51]
是python3的问题吗？ 为啥我运行会是这样。。。（截取片段

------------------------------------------------------------------------
哪一种茶不属于绿茶?
------------------------------------------------------------------------
安吉白片
太平猴
老青茶
'locale' codec can't encode character '\u5e74' in position 2: Illegal byte sequence
欢迎下次使用

**Comment by NSDie** [comment]
是不是要加句 locale的配置

**Comment by smileboywtu** [comment]
谢谢 对项目的关注 现在在改进中

**Comment by smileboywtu** [comment]
您好 给你带来不便 目前已经修复测试了请在试一试 哦
