### ISSUE TITLE
刚才百万英雄一点场, 给的答案好多都是错的...

### ISSUE THREAD

**Issue by dupl10** [smileboywtu/MillionHeroAssistant#54]
如题......

**Comment by jozhn** [comment]
本来就只是参考的，搜索引擎的结果数量当然不是很靠谱。你提issue可以提出更好的算法嘛。。。

**Comment by smileboywtu** [comment]
你好，谢谢反馈，算法在不断改进中，但是题目也越来越 绕，目前只能给出综合结果，你优先考虑 推荐答案，然后再是知识图谱，最后才是浏览器，新版本筹划中，但是估计源码不开源了，感觉被出题人看懂了

**Comment by smileboywtu** [comment]
会给一个二进制直接运行，整个活动结束后在给出源码学习

**Comment by dupl10** [comment]
log when, 求免费的二进制.

**Comment by smileboywtu** [comment]
@dupl10 你联系我把微信
