### ISSUE TITLE
你好作者

### ISSUE THREAD

**Issue by Wbqqqq** [smileboywtu/MillionHeroAssistant#55]
我是一个python的初学者,我在学习你的代码过程中，并没有发现你在当中用到你readme里所说的V2 文本关联相似度分析的算法。而是看到你直接在搜索的结果当中，用了答案匹配出来的同比列表，是不是这样的呢 感谢作者答疑解惑 🙏

**Comment by smileboywtu** [comment]
请看knearby分支谢谢，你说的那个方法在分支上面
