### ISSUE TITLE
ERROR:process_metrics.cc(105)] NOT IMPLEMENTED问题的请看这里

### ISSUE THREAD

**Issue by joln** [smileboywtu/MillionHeroAssistant#56]
有类似的issues讨论过这个问题了。 是Chrome v63版本的问题，简单来说就是将 Chrome v63的版本到低版本
看这里[https://github.com/SeleniumHQ/selenium/issues/5189#issuecomment-351605839](https://github.com/SeleniumHQ/selenium/issues/5189#issuecomment-351605839)

**Comment by smileboywtu** [comment]
是升级 我用的chromedriver适配63-65 不是降低，最好能升级

**Comment by smileboywtu** [comment]
目前升级可以解决，故关闭这个issue
