### ISSUE TITLE
出现list out of range错误

### ISSUE THREAD

**Issue by Deancup** [smileboywtu/MillionHeroAssistant#60]
![image](https://user-images.githubusercontent.com/25227084/35044750-802d5a50-fbcc-11e7-8767-b91cf843fb5d.png)

![image](https://user-images.githubusercontent.com/25227084/35044762-8890ef5e-fbcc-11e7-8053-6ea971deb872.png)

**Comment by smileboywtu** [comment]
这个是百度识别的问题。能否给出源图片

**Comment by smileboywtu** [comment]
麻烦加qq后联系具体的问题

**Comment by smileboywtu** [comment]
请使用新版本，有问题再次提交issue
