### ISSUE TITLE
ios版识别不出来文字啊，第二次打开还卡住了

### ISSUE THREAD

**Issue by maltsugar** [smileboywtu/MillionHeroAssistant#7]

**Comment by smileboywtu** [comment]
连接是正常的吗

**Comment by smileboywtu** [comment]
进群交流把  或者你检查下 汉王或者百度的api code 最好用你自己的，可能已经用完了

**Comment by maltsugar** [comment]
连接正常啊  有时候能用

**Comment by UniqHu** [comment]
首先要判断问题出现在哪一步.  wda正常吗, 端口转发打开之后有没有测试过 http://localhost:8100/status,  又返回结果吗?   sh ./Scripts/bootstrap.sh  必须提前开启,    cmd+u后iPhone会有app,

**Comment by smileboywtu** [comment]
微信群里面解决了 关闭issue
