### ISSUE TITLE
你们运行了最新版本吗？

### ISSUE THREAD

**Issue by Agnon1573** [smileboywtu/MillionHeroAssistant#70]
怎么用最新的好像不怎么好用啊！是我的问题吗？我用orcspace的时候根本就没有任何输出，用百度orc的时候在芝士超人上感觉运行的好慢，虽然芝士超人那个软件也卡的不要不要的！暂时没有在西瓜视频上实验，先还是使用原来的版本吧！

**Comment by lweo** [comment]
google的orcspace不要翻墙吗？
