### ISSUE TITLE
requirements.txt安装出错

### ISSUE THREAD

**Issue by snhun** [smileboywtu/MillionHeroAssistant#72]
Command "e:\others\python\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\snhun\\AppData\\Local\\Temp\\pip-build-ngn73xop\\scikit-image\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\snhun\AppData\Local\Temp\pip-ovnw4jtd-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\snhun\AppData\Local\Temp\pip-build-ngn73xop\scikit-image\

**Comment by Agnon1573** [comment]
没有必要安装vc++可以去直接下skit-image的whl文件后直接安装即可

**Comment by Agnon1573** [comment]
下载地址：https://www.lfd.uci.edu/~gohlke/pythonlibs/#scikit-image

**Comment by snhun** [comment]
多谢楼上两位解答分享。
