### ISSUE TITLE
安装requirements.txt提示TypeError: string argument expected, got 'NoneType'

### ISSUE THREAD

**Issue by zzugyl** [smileboywtu/MillionHeroAssistant#73]
Python3.6.4  pip9.0.1
` ➤ pip install -r requirements.txt
pip install -r requirements.txt
Requirement already satisfied: beautifulsoup4==4.6.0 in d:\python\python36-32\lib\site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: certifi==2017.11.5 in d:\python\python36-32\lib\site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: chardet==3.0.4 in d:\python\python36-32\lib\site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: future==0.16.0 in d:\python\python36-32\lib\site-packages (from -r requirements.txt (line 5))
Requirement already satisfied: idna==2.6 in d:\python\python36-32\lib\site-packages (from -r requirements.txt (line 6))
Requirement already satisfied: jieba==0.39 in d:\python\python36-32\lib\site-packages (from -r requirements.txt (line 7))
Requirement already satisfied: lxml==4.1.1 in d:\python\python36-32\lib\site-packages (from -r requirements.txt (line 8))
Requirement already satisfied: macholib==1.9 in d:\python\python36-32\lib\site-packages (from -r requirements.txt (line 9))
Requirement already satisfied: pefile==2017.11.5 in d:\python\python36-32\lib\site-packages (from -r requirements.txt (line 10))
Requirement already satisfied: Pillow==5.0.0 in d:\python\python36-32\lib\site-packages (from -r requirements.txt (line 11))
Requirement already satisfied: PyYAML==3.12 in d:\python\python36-32\lib\site-packages (from -r requirements.txt (line 12))
Exception:
Traceback (most recent call last):
  File "d:\python\python36-32\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "d:\python\python36-32\lib\site-packages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "d:\python\python36-32\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "d:\python\python36-32\lib\site-packages\pip\req\req_set.py", line 666, in _prepare_file
    check_dist_requires_python(dist)
  File "d:\python\python36-32\lib\site-packages\pip\utils\packaging.py", line 48, in check_dist_requires_python
    feed_parser.feed(metadata)
  File "d:\python\python36-32\lib\email\feedparser.py", line 175, in feed
    self._input.push(data)
  File "d:\python\python36-32\lib\email\feedparser.py", line 103, in push
    self._partial.write(data)
TypeError: string argument expected, got 'NoneType'

**Comment by smileboywtu** [comment]
这个问题 好像是没遇到过，你挨个安装试一试 看是那个包报错了

**Comment by zzugyl** [comment]
估计是默认Python2的缘故。
我换pip3 install -r requirements.txt就顺利执行了。

**Comment by zzugyl** [comment]
还一个可能性就是64位系统，安装了32位的Python。
