### ISSUE TITLE
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

### ISSUE THREAD

**Issue by smartleon** [smileboywtu/MillionHeroAssistant#75]
这个问题该怎么解决？必须安装14.0？还是自动安装脚本有问题？    
----------------------------------------
Command "c:\users\smartleon\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\SMARTL~1\\AppData\\Local\\Temp\\pip-build-miajq4w8\\scikit-image\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\SMARTL~1\AppData\Local\Temp\pip-qpxoysl6-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\SMARTL~1\AppData\Local\Temp\pip-build-miajq4w8\scikit-image\

**Comment by lweo** [comment]
微软官网下载安装Visual C++ Build Tools或下以编译好的包https://www.lfd.uci.edu/~gohlke/pythonlibs/#scikit-image（自行判断32位或64位包）
然后在文件所在目录，管理员权限打开命令窗口
pippip install 文件名.whl

**Comment by smileboywtu** [comment]
两种方法都可以的
